// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Game struct {
	ID                    int64
	GroupID               int64
	GameNum               int64
	TranscentisID         string
	TargetSurplus         int64
	TargetRetailerCost    int64
	TargetSupplyChainCost int64
}

type Group struct {
	ID   int64
	Name string
}

type SupplyChainWeekly struct {
	ID      int64
	GameID  int64
	Week    int64
	CostAcc float64
}

type WeeklyStat struct {
	ID               int64
	GameID           int64
	Week             int64
	Role             string
	ActualOrder      int64
	OpenOrders       int64
	Inventory        int64
	Backorder        int64
	IncomingDelivery int64
	IncomingOrder    int64
	OutgoingDelivery int64
	Surplus          int64
	Cost             float64
	CostAcc          float64
}
