// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const insertGame = `-- name: InsertGame :one
INSERT INTO games (group_id, game_num, transcentis_id, target_surplus, target_retailer_cost, target_supply_chain_cost)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
RETURNING id
`

type InsertGameParams struct {
	GroupID               int64
	GameNum               int64
	TranscentisID         string
	TargetSurplus         int64
	TargetRetailerCost    int64
	TargetSupplyChainCost int64
}

// noinspection SqlResolve
func (q *Queries) InsertGame(ctx context.Context, arg InsertGameParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertGame,
		arg.GroupID,
		arg.GameNum,
		arg.TranscentisID,
		arg.TargetSurplus,
		arg.TargetRetailerCost,
		arg.TargetSupplyChainCost,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertSupplyChainWeekly = `-- name: InsertSupplyChainWeekly :exec
INSERT INTO supply_chain_weekly (game_id, week, cost_acc)
VALUES (?1, ?2, ?3)
`

type InsertSupplyChainWeeklyParams struct {
	GameID  int64
	Week    int64
	CostAcc float64
}

// noinspection SqlResolve
func (q *Queries) InsertSupplyChainWeekly(ctx context.Context, arg InsertSupplyChainWeeklyParams) error {
	_, err := q.db.ExecContext(ctx, insertSupplyChainWeekly, arg.GameID, arg.Week, arg.CostAcc)
	return err
}

const insertWeeklyStat = `-- name: InsertWeeklyStat :exec
INSERT INTO weekly_stats (game_id, week, role, actual_order, open_orders, inventory, backorder, incoming_delivery, incoming_order, outgoing_delivery, surplus, cost, cost_acc)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13)
`

type InsertWeeklyStatParams struct {
	GameID           int64
	Week             int64
	Role             string
	ActualOrder      int64
	OpenOrders       int64
	Inventory        int64
	Backorder        int64
	IncomingDelivery int64
	IncomingOrder    int64
	OutgoingDelivery int64
	Surplus          int64
	Cost             float64
	CostAcc          float64
}

// noinspection SqlResolve
func (q *Queries) InsertWeeklyStat(ctx context.Context, arg InsertWeeklyStatParams) error {
	_, err := q.db.ExecContext(ctx, insertWeeklyStat,
		arg.GameID,
		arg.Week,
		arg.Role,
		arg.ActualOrder,
		arg.OpenOrders,
		arg.Inventory,
		arg.Backorder,
		arg.IncomingDelivery,
		arg.IncomingOrder,
		arg.OutgoingDelivery,
		arg.Surplus,
		arg.Cost,
		arg.CostAcc,
	)
	return err
}

const upsertGroup = `-- name: UpsertGroup :one
INSERT INTO groups (name)
VALUES (?1)
ON CONFLICT(name) DO UPDATE SET name = name
RETURNING id
`

// noinspection SqlResolve
func (q *Queries) UpsertGroup(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertGroup, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}
